# Generated by Django 4.2 on 2023-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
